<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
  
  <!-- Properties -->
  <xacro:property name="chassis_length" value="0.335"/>
  <xacro:property name="chassis_width" value="0.265"/>
  <xacro:property name="chassis_height" value="0.138"/>
  
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_thickness" value="0.026"/>
  <xacro:property name="wheel_mass" value="0.05"/>
  
  <xacro:property name="front_wheel_offset_x" value="0.113"/>
  <xacro:property name="rear_wheel_offset_x" value="-0.113"/>
  <xacro:property name="wheel_offset_y" value="0.1485"/>
  
  <xacro:property name="caster_wheel_radius" value="0.01"/>
  <xacro:property name="caster_wheel_mass" value="0.01"/>
  <xacro:property name="caster_wheel_offset_x" value="0.075"/>
  
  <xacro:property name="mass" value="1.0"/>
  
  <!-- Materials -->
  <material name="white">
    <color rgba="1 1 1 1" />
  </material>
  <material name="orange">
    <color rgba="1 0.3 0.1 1"/>
  </material>
  <material name="blue">
    <color rgba="0.2 0.2 1 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <!-- Main chassis link that contains the robot body -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <mass value="${mass}" />
      <inertia 
        ixx="${(1/12) * mass * (chassis_width*chassis_width+chassis_height*chassis_height)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * mass * (chassis_length*chassis_length+chassis_height*chassis_height)}"
        iyz="0.0"
        izz="${(1/12) * mass * (chassis_length*chassis_length+chassis_width*chassis_width)}"
      />
    </inertial>
    <visual>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Orange</material>
  </gazebo>

  <link name="base_footprint">
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 -${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Front Left Wheel -->
  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="${front_wheel_offset_x} ${wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="front_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}" />
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="front_left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Front Right Wheel -->
  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="${front_wheel_offset_x} ${-wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="front_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}" />
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="front_right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Rear Left Wheel -->
  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz="${rear_wheel_offset_x} ${wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="rear_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}" />
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="rear_left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Rear Right Wheel -->
  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz="${rear_wheel_offset_x} ${-wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="rear_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}" />
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="rear_right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Caster Wheel -->
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${caster_wheel_offset_x} 0 -${chassis_height/2 + caster_wheel_radius}"/>
  </joint>

  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${caster_wheel_mass}" />
      <inertia 
        ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}"
        iyz="0.0"
        izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="caster_wheel">
    <material>Gazebo/White</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>

</robot>