<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
  
  <!-- Properties -->
  <xacro:property name="chassis_length" value="0.335"/>
  <xacro:property name="chassis_width" value="0.265"/>
  <xacro:property name="chassis_height" value="0.138"/>
  
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_thickness" value="0.026"/>
  <xacro:property name="wheel_mass" value="0.05"/>
  
  <xacro:property name="front_wheel_offset_x" value="0.113"/>
  <xacro:property name="rear_wheel_offset_x" value="-0.113"/>
  <xacro:property name="wheel_offset_y" value="0.1485"/>
  
  <xacro:property name="mass" value="1.0"/>
  
  <!-- New properties for steam locomotive elements -->
  <xacro:property name="pipe_radius" value="${chassis_width/4}"/>
  <xacro:property name="pipe_height" value="0.15"/>
  <xacro:property name="cabin_wall_thickness" value="0.015"/>
  <xacro:property name="cabin_wall_height" value="0.08"/>
  <xacro:property name="cabin_roof_thickness" value="0.02"/>
  <xacro:property name="cabin_length" value="${chassis_length/3}"/>
  
  <!-- Materials -->
  <material name="white">
    <color rgba="1 1 1 1" />
  </material>
  <material name="orange">
    <color rgba="1 0.3 0.1 1"/>
  </material>
  <material name="blue">
    <color rgba="0.2 0.2 1 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1"/>
  </material>
  <material name="glass">
    <color rgba="0.7 0.9 1.0 0.6"/>
  </material>

  <!-- Main chassis link that contains the robot body -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <mass value="${mass}" />
      <inertia 
        ixx="${(1/12) * mass * (chassis_width*chassis_width+chassis_height*chassis_height)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * mass * (chassis_length*chassis_length+chassis_height*chassis_height)}"
        iyz="0.0"
        izz="${(1/12) * mass * (chassis_length*chassis_length+chassis_width*chassis_width)}"
      />
    </inertial>
    <visual>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Orange</material>
  </gazebo>

  <link name="base_footprint">
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 -${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Steam Pipe (moved closer to cabin, front edge aligned with chassis front) -->
  <link name="steam_pipe">
    <inertial>
      <origin xyz="0 0 ${pipe_height/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia 
        ixx="${(1/12) * 0.1 * (3*pipe_radius*pipe_radius + pipe_height*pipe_height)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * 0.1 * (3*pipe_radius*pipe_radius + pipe_height*pipe_height)}"
        iyz="0.0"
        izz="${(1/2) * 0.1 * (pipe_radius*pipe_radius)}"
      />
    </inertial>
    <visual>
      <origin xyz="0 0 ${pipe_height/2}"/>
      <geometry>
        <cylinder radius="${pipe_radius}" length="${pipe_height}"/>
      </geometry>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${pipe_height/2}"/>
      <geometry>
        <cylinder radius="${pipe_radius}" length="${pipe_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="steam_pipe_joint" type="fixed">
    <parent link="base_link"/>
    <child link="steam_pipe"/>
    <origin xyz="${chassis_length/2 - pipe_radius} 0 ${chassis_height}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="steam_pipe">
    <material>Gazebo/DarkGray</material>
  </gazebo>

  <!-- Cabin Left Wall (full width at the edges) -->
  <link name="cabin_left_wall">
    <inertial>
      <origin xyz="0 0 ${cabin_wall_height/2}" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia 
        ixx="${(1/12) * 0.05 * (cabin_wall_thickness*cabin_wall_thickness + cabin_wall_height*cabin_wall_height)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * 0.05 * (cabin_length*cabin_length + cabin_wall_height*cabin_wall_height)}"
        iyz="0.0"
        izz="${(1/12) * 0.05 * (cabin_length*cabin_length + cabin_wall_thickness*cabin_wall_thickness)}"
      />
    </inertial>
    <visual>
      <origin xyz="0 0 ${cabin_wall_height/2}"/>
      <geometry>
        <box size="${cabin_length} ${cabin_wall_thickness} ${cabin_wall_height}"/>
      </geometry>
      <material name="glass"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${cabin_wall_height/2}"/>
      <geometry>
        <box size="${cabin_length} ${cabin_wall_thickness} ${cabin_wall_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="cabin_left_wall_joint" type="fixed">
    <parent link="base_link"/>
    <child link="cabin_left_wall"/>
    <origin xyz="${-chassis_length/3} ${chassis_width/2 - cabin_wall_thickness/2} ${chassis_height}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="cabin_left_wall">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Cabin Right Wall (full width at the edges) -->
  <link name="cabin_right_wall">
    <inertial>
      <origin xyz="0 0 ${cabin_wall_height/2}" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia 
        ixx="${(1/12) * 0.05 * (cabin_wall_thickness*cabin_wall_thickness + cabin_wall_height*cabin_wall_height)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * 0.05 * (cabin_length*cabin_length + cabin_wall_height*cabin_wall_height)}"
        iyz="0.0"
        izz="${(1/12) * 0.05 * (cabin_length*cabin_length + cabin_wall_thickness*cabin_wall_thickness)}"
      />
    </inertial>
    <visual>
      <origin xyz="0 0 ${cabin_wall_height/2}"/>
      <geometry>
        <box size="${cabin_length} ${cabin_wall_thickness} ${cabin_wall_height}"/>
      </geometry>
      <material name="glass"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${cabin_wall_height/2}"/>
      <geometry>
        <box size="${cabin_length} ${cabin_wall_thickness} ${cabin_wall_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="cabin_right_wall_joint" type="fixed">
    <parent link="base_link"/>
    <child link="cabin_right_wall"/>
    <origin xyz="${-chassis_length/3} ${-chassis_width/2 + cabin_wall_thickness/2} ${chassis_height}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="cabin_right_wall">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Cabin Roof (full width of chassis, touching the walls) -->
  <link name="cabin_roof">
    <inertial>
      <origin xyz="0 0 ${cabin_roof_thickness/2}" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia 
        ixx="${(1/12) * 0.1 * (cabin_roof_thickness*cabin_roof_thickness + chassis_width*chassis_width)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * 0.1 * (cabin_length*cabin_length + chassis_width*chassis_width)}"
        iyz="0.0"
        izz="${(1/12) * 0.1 * (cabin_length*cabin_length + cabin_roof_thickness*cabin_roof_thickness)}"
      />
    </inertial>
    <visual>
      <origin xyz="0 0 ${cabin_roof_thickness/2}"/>
      <geometry>
        <box size="${cabin_length} ${chassis_width} ${cabin_roof_thickness}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${cabin_roof_thickness/2}"/>
      <geometry>
        <box size="${cabin_length} ${chassis_width} ${cabin_roof_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="cabin_roof_joint" type="fixed">
    <parent link="base_link"/>
    <child link="cabin_roof"/>
    <!-- Adjusted to ensure roof touches the walls -->
    <origin xyz="${-chassis_length/3} 0 ${chassis_height + cabin_wall_height}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="cabin_roof">
    <material>Gazebo/Gray</material>
  </gazebo>

  <!-- Wheels (unchanged) -->
  <!-- Front Left Wheel -->
  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="${front_wheel_offset_x} ${wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="front_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}" />
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="front_left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Front Right Wheel -->
  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="${front_wheel_offset_x} ${-wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="front_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}" />
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="front_right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Rear Left Wheel -->
  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz="${rear_wheel_offset_x} ${wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="rear_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}" />
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="rear_left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Rear Right Wheel -->
  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz="${rear_wheel_offset_x} ${-wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="rear_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}" />
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"
      />
    </inertial>
  </link>

  <gazebo reference="rear_right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>